name: Test

on:
  push:
    branches:
      - '*'

jobs:
  dummy:
    runs-on: ubuntu-latest

    steps:
      - name: Dummy step
        run: echo "This is a dummy step to ensure the workflow contains at least one job with no dependencies"

  test:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.14'

    - name: Install dependencies
      run: npm ci

    - name: Install playwright browsers
      run: npx playwright install --with-deps

    - name: Run tests
      run: npm run test

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/junit-test-results.xml'
